# fly.toml app configuration file generated for summer-sun-5919 on 2023-07-17T21:17:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-sun-5919"
primary_region = "dfw"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
